gzip secrets data
digitalocean/fluentbit-operator pull request #10
Opened 2021-10-25 12:07 UTC by bojand

`fluentbit-operator` uses a secret to store a global config file for fluent bit pods.

Data in Kubernetes secrets have [1MiB size limit](https://kubernetes.io/docs/concepts/configuration/secret/#details) which can be problematic in scenarios where we have a single config and daemonset for a cluster.

**Context**

`fluent-bit-watcher` docker image [copies a default fluent-bit config](https://github.com/digitalocean/fluentbit-operator/blob/master/cmd/fluent-bit-watcher/Dockerfile#L12) into `/fluent-bit/etc/`, sourced from files in [conf folder](https://github.com/digitalocean/fluentbit-operator/tree/master/conf), specifically, the [fluent-bit config file](https://github.com/digitalocean/fluentbit-operator/blob/master/conf/fluent-bit.conf) is simply:

```
@INCLUDE /fluent-bit/config/fluent-bit.conf
```

where `/fluent-bit/config/fluent-bit.conf` is the config rendered by the operator and attached to `fluent-bit-watcher` pods via the secret.

**Changes**

- Add `gziputil` package that adds functions for compressing and decompressing data
- Add `use-compression` option to `operator`
- When compression option is used, operator compresses the rendered config file in the secret
- Adds scratch space volume to fluent bit daemonset
- In `fluent-bit-watcher` we detect if the config is compressed. If it is we decompress it into the scratch space, and use that as the config file for the actual fluent bit process.

2021-10-25 13:46 UTC, Shahar-Levy approved these changes
Nice!

2021-10-25 13:46 UTC, Shahar-Levy commented on cmd/fluent-bit-watcher/main.go
> +	configFilePath := configPath
I was confused trying to understand why this variable is duplicated with an almost identical name. It seems like if the file is compressed, we overwrite this using `scratchCfgPath` and if it isn't, we wont. Nit: would we be able to add a comment explaining the need for this variable? Alternatively, would it alright to overwrite the `configpath` so only one variable has the config path?

2021-10-25 13:46 UTC, Shahar-Levy commented on pkg/gziputil/compress.go
> +var magicGzip = []byte{0x1f, 0x8b, 0x08}
silly go question, but what is this doing?

2021-10-25 13:48 UTC, Shahar-Levy commented
Am I understanding this right when I see that this is either enabled or disabled, but doesn't detect whether we are approaching the 1MiB object limit?

2021-10-25 22:46 UTC, bojand commented on cmd/fluent-bit-watcher/main.go
> +	configFilePath := configPath
`configPath` is the fluent bit configuration path set by user via `-c` flag, so we do not want to be overwriting that since we need to know what it is.
`configFilePath` variable is for the config path _we will_ use to pass to fluent-bit process.
 We are essentially checking if the configuration file is compressed, if it is we decompress it to a different path, and set the `configFilePath` to that new path, otherwise `configFilePath` should be `configPath`.

2021-10-25 22:49 UTC, bojand commented on pkg/gziputil/compress.go
> +var magicGzip = []byte{0x1f, 0x8b, 0x08}
This is [gzip magic](https://en.wikipedia.org/wiki/Gzip) that's part of the gzip file format header:
> a 10-byte header, containing a magic number (1f 8b), the compression method (08 for DEFLATE), 1-byte of header flags, a 4-byte timestamp, compression flags and the operating system ID.

Every gzip file starts with those bytes.

2021-10-25 22:51 UTC, bojand commented
Yup this enables us to compress the secret data in the operator, and also read the compressed file on the fluent-bit side. 
I suppose we could do a length check on the secrets data in the operator and print out a warming if over some limit that's approaching 1MiB. That might not be a bad idea.

2021-10-26 13:12 UTC, Shahar-Levy commented on pkg/gziputil/compress.go
> +var magicGzip = []byte{0x1f, 0x8b, 0x08}
TIL. Neat, thanks!

2021-10-26 17:09 UTC, nicktate requested changes

2021-10-26 17:09 UTC, nicktate commented on controllers/fluentbitconfig_controller.go
> +	UseCompresstion bool
nit: spelling
```suggestion
	UseCompression bool
```

2021-10-26 17:09 UTC, nicktate commented on pkg/gziputil/compress.go
> +	w.Close()
we should defer close before writing so we don't leak the writer if we fail to write

2021-10-26 17:09 UTC, nicktate commented on cmd/fluent-bit-watcher/main.go
> +	configFilePath := configPath
So from what I understand, by default `configPath` points to a static conf `/fluent-bit/etc/fluent-bit.conf` (copied during the dockerfile build) with an `@INCLUDE` directive pointing to `/fluent-bit/config/fluent-bit.conf`: https://github.com/digitalocean/fluentbit-operator/blob/master/conf/fluent-bit.conf. 

The actual data that is compressed will be what is mounted under `/fluent-bit-config/` and ultimately what we have the watcher process monitoring for changes. I think we need to update this logic to check compression against `/fluent-bit/config/fluent-bit.conf`. The file we are currently checking is effectively a plain-text symlink that won't change.

2021-10-27 02:56 UTC, bojand commented on pkg/gziputil/compress.go
> +	w.Close()
This causes issues with the `Bytes()` call below. We need to flush with `Close()` first in order to have the data to return.

2021-10-27 21:05 UTC, nicktate approved these changes
Looks good overall; pre-approving **but** I do think the scratch config file is incorrectly set and needs to be resolved before merging.

2021-10-27 21:05 UTC, nicktate commented on cmd/fluent-bit-watcher/main.go
> +	scratchCfgPath = "/tmp/fluent-bit"
nit: might be worth calling this `scratchCfgDir` rather than `Path` since the path references the actual file in other variables.

2021-10-27 21:05 UTC, nicktate commented on cmd/fluent-bit-watcher/main.go
> +		configFilePath = scratchCfgPath
shouldn't this be `configFilePath = newConfig`?

2021-10-28 18:55 UTC, merged